// _lib.mjs — shared helpers for Netlify functions.
import { randomUUID } from 'crypto';
import { db } from '../../db/index.js';
import { auditLog, users } from '../../db/schema.js';
import { eq } from 'drizzle-orm';

// Browser origins allowed to call the API. Kept in sync with the Clerk
// authorizedParties list in auth.mjs. Exported for the CORS follow-up; any
// origin not on this list already fails Clerk auth.
export const ALLOWED_ORIGINS = [
    'https://salespipelinetracker.com',
    'https://sales-pipeline-v2.netlify.app',
    'https://accelerep.netlify.app',
    'http://localhost:5173',
    'http://localhost:8888',
];
const PRIMARY_ORIGIN = 'https://salespipelinetracker.com';

// Echo the caller's origin only if allow-listed; otherwise the primary domain.
export function allowOrigin(event) {
    const origin = event?.headers?.origin || event?.headers?.Origin || '';
    return ALLOWED_ORIGINS.includes(origin) ? origin : PRIMARY_ORIGIN;
}

// Standardized 500 body: logs the real error server-side with a correlation id
// and returns ONLY a generic message + that id to the client, so DB driver text
// and stack traces never leak. Returns the JSON string for use as a 500 body.
export function serverErrorBody(err, label = 'function') {
    const requestId = randomUUID();
    console.error(`[${label}] error ${requestId}:`, err?.message, err?.stack);
    return JSON.stringify({ error: 'Internal server error', requestId });
}

// Best-effort audit-log writer shared by entity endpoints. Never throws —
// an audit failure must not fail (or roll back the visibility of) the
// operation being audited; it is logged server-side instead.
export async function writeAudit(orgId, { action, entityType, entityId, entityName = null, detail = null, userId = null, userName = null }) {
    try {
        await db.insert(auditLog).values({
            id: 'audit_' + randomUUID(),
            orgId,
            action,
            entityType,
            entityId: String(entityId || ''),
            entityName,
            detail,
            userId,
            userName,
            timestamp: new Date(),
        });
    } catch (e) {
        console.warn('writeAudit error:', e.message);
    }
}

// Resolve the caller's display name for name-based ownership checks.
// Entity ownership fields (salesRep, accountOwner, assignedTo, repName,
// createdBy) store display names, not Clerk userIds, so object-level write
// authorization compares against this. Cached briefly (per warm container)
// since it runs on every rep-role mutation. Returns null on miss/error —
// callers treat null as "does not own any assigned record" (fail closed).
const callerNameCache = new Map();
const CALLER_NAME_TTL_MS = 30_000;
export async function getCallerName(userId) {
    if (!userId) return null;
    const cached = callerNameCache.get(userId);
    if (cached && Date.now() - cached.ts < CALLER_NAME_TTL_MS) return cached.name;
    try {
        const [row] = await db.select({ name: users.name }).from(users).where(eq(users.id, userId));
        const name = row?.name || null;
        callerNameCache.set(userId, { name, ts: Date.now() });
        if (callerNameCache.size > 500) callerNameCache.delete(callerNameCache.keys().next().value);
        return name;
    } catch (e) {
        console.warn('getCallerName error:', e.message);
        return null;
    }
}

// ── Sequential record numbers ────────────────────────────────────────────────
// CUST-0001 / JOB-2026-0042 / Q-2026-001 are all generated by reading the current
// maximum and adding one. That is two statements with a gap between them, so two
// concurrent requests can read the same maximum and both write the same number.
//
// The unique indexes in schema.ts turn that silent duplicate into a Postgres
// unique_violation (SQLSTATE 23505). This helper is the other half: it retries,
// so the loser of the race simply takes the next number instead of erroring.
//
// Only 23505 is retried. Any other failure is a real error and is rethrown
// immediately rather than being retried into a timeout.
const isUniqueViolation = (err) =>
    err?.code === '23505' ||
    err?.cause?.code === '23505' ||
    /duplicate key value violates unique constraint/i.test(err?.message || '');

export async function withNumberRetry(attempt, { tries = 5, label = 'record number' } = {}) {
    let lastErr;
    for (let i = 0; i < tries; i++) {
        try {
            return await attempt(i);
        } catch (err) {
            if (!isUniqueViolation(err)) throw err;
            lastErr = err;
            // Small jittered backoff so simultaneous callers do not re-collide in
            // lockstep on the retry.
            await new Promise(r => setTimeout(r, 10 + Math.floor(Math.random() * 40)));
        }
    }
    const e = new Error(`Could not assign a unique ${label} after ${tries} attempts. Please try again.`);
    e.cause = lastErr;
    throw e;
}
