[functions."digest"]
schedule = "0 * * * *"

[functions."pipeline-alerts"]
schedule = "0 * * * *"

[functions."task-reminders"]
schedule = "* * * * *"

[[redirects]]
from = "/api=docs.html"
to = "/api-docs.hrml"
status = 200
force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
