import {
    pgTable, text, integer, boolean, timestamp, jsonb, varchar, decimal
} from 'drizzle-orm/pg-core';
// ── USERS ─────────────────────────────────────────────────────────────────────
// Sales reps, managers, admins — one row per user account
export const users = pgTable('users', {
    id:            text('id').primaryKey(),                          // e.g. "usr_001"
    name:          varchar('name', { length: 255 }).notNull(),
    email:         varchar('email', { length: 255 }).notNull().unique(),
    role:          varchar('role', { length: 50 }).notNull().default('User'),  // Admin | Manager | User | ReadOnly
    team:          varchar('team', { length: 255 }),
    territory:     varchar('territory', { length: 255 }),
    quota:         decimal('quota', { precision: 12, scale: 2 }),
    active:        boolean('active').notNull().default(true),
    profile:       jsonb('profile').default('{}'),                   // full profile fields (firstName, lastName, phone, etc.)
    createdAt:     timestamp('created_at').notNull().defaultNow(),
    orgId:         text('org_id').notNull(),
    updatedAt:     timestamp('updated_at').notNull().defaultNow(),
});
// ── PIPELINES ─────────────────────────────────────────────────────────────────
export const pipelines = pgTable('pipelines', {
    id:        text('id').primaryKey(),
    orgId:     text('org_id').notNull(),
    name:      varchar('name', { length: 255 }).notNull(),
    isDefault: boolean('is_default').notNull().default(false),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
});
// ── ACCOUNTS ──────────────────────────────────────────────────────────────────
export const accounts = pgTable('accounts', {
    id:                text('id').primaryKey(),
    name:              varchar('name', { length: 255 }).notNull(),
    verticalMarket:    varchar('vertical_market', { length: 255 }),
    industry:          varchar('industry', { length: 255 }),
    address:           text('address'),
    city:              varchar('city', { length: 255 }),
    state:             varchar('state', { length: 100 }),
    zip:               varchar('zip', { length: 20 }),
    country:           varchar('country', { length: 100 }),
    website:           varchar('website', { length: 500 }),
    phone:             varchar('phone', { length: 50 }),
    accountOwner:      varchar('account_owner', { length: 255 }),
    assignedRep:       varchar('assigned_rep', { length: 255 }),
    assignedTerritory: varchar('assigned_territory', { length: 255 }),
    parentAccountId:   text('parent_account_id'),
    accountTier:       varchar('account_tier', { length: 20 }).default('account'),
    address2:          varchar('address2', { length: 255 }),
    notes:             text('notes'),
    doNotContact:      boolean('do_not_contact').default(false),
    customerTypes:     jsonb('customer_types').default('[]'),
    accountSegment:    varchar('account_segment', { length: 100 }),  // SMB / Mid-Market / Enterprise etc.
    // Account Details tab fields
    description:       text('description'),
    totalEmployees:    varchar('total_employees', { length: 20 }),
    annualRevenue:     varchar('annual_revenue', { length: 50 }),
    fiscalYearEnd:     varchar('fiscal_year_end', { length: 2 }),
    foundedYear:       varchar('founded_year', { length: 4 }),
    linkedInUrl:       varchar('linked_in_url', { length: 500 }),
    sicCode:           varchar('sic_code', { length: 6 }),
    naicsCode:         varchar('naics_code', { length: 8 }),
    createdAt:         timestamp('created_at').notNull().defaultNow(),
    orgId:             text('org_id').notNull(),
    updatedAt:         timestamp('updated_at').notNull().defaultNow(),
});
// ── CONTACTS ──────────────────────────────────────────────────────────────────
export const contacts = pgTable('contacts', {
    id:                text('id').primaryKey(),
    prefix:            varchar('prefix', { length: 20 }),
    firstName:         varchar('first_name', { length: 255 }),
    middleName:        varchar('middle_name', { length: 255 }),
    lastName:          varchar('last_name', { length: 255 }),
    suffix:            varchar('suffix', { length: 20 }),
    nickName:          varchar('nick_name', { length: 255 }),
    title:             varchar('title', { length: 255 }),
    company:           varchar('company', { length: 255 }),
    department:        varchar('department', { length: 255 }),
    workLocation:      varchar('work_location', { length: 255 }),
    email:             varchar('email', { length: 255 }),
    personalEmail:     varchar('personal_email', { length: 255 }),
    phone:             varchar('phone', { length: 50 }),
    mobile:            varchar('mobile', { length: 50 }),
    address:           text('address'),
    city:              varchar('city', { length: 255 }),
    state:             varchar('state', { length: 100 }),
    zip:               varchar('zip', { length: 20 }),
    country:           varchar('country', { length: 100 }),
    managers:          jsonb('managers').default('[]'),
    directReports:     jsonb('direct_reports').default('[]'),
    assistantName:     varchar('assistant_name', { length: 255 }),
    homeAddress:       text('home_address'),
    notes:             text('notes'),
    assignedRep:       varchar('assigned_rep', { length: 255 }),
    assignedTerritory: varchar('assigned_territory', { length: 255 }),
    doNotContact:      boolean('do_not_contact').default(false),
    createdAt:         timestamp('created_at').notNull().defaultNow(),
    orgId:             text('org_id').notNull(),
    updatedAt:         timestamp('updated_at').notNull().defaultNow(),
});
// ── OPPORTUNITIES ─────────────────────────────────────────────────────────────
export const opportunities = pgTable('opportunities', {
    id:                   text('id').primaryKey(),
    pipelineId:           text('pipeline_id').notNull(),
    opportunityName:      varchar('opportunity_name', { length: 500 }),
    account:              varchar('account', { length: 255 }),
    site:                 varchar('site', { length: 255 }),
    salesRep:             varchar('sales_rep', { length: 255 }),
    stage:                varchar('stage', { length: 100 }).notNull(),
    arr:                  decimal('arr', { precision: 12, scale: 2 }),
    implementationCost:   decimal('implementation_cost', { precision: 12, scale: 2 }),
    forecastedCloseDate:  varchar('forecasted_close_date', { length: 20 }),
    closeQuarter:         varchar('close_quarter', { length: 50 }),
    products:             text('products'),
    unionized:            varchar('unionized', { length: 10 }),
    painPoints:           text('pain_points'),
    contacts:             text('contacts'),
    contactIds:           jsonb('contact_ids').default('[]'),
    notes:                text('notes'),
    nextSteps:            text('next_steps'),
    probability:          integer('probability'),
    forecastCategory:     varchar('forecast_category', { length: 100 }),
    vertical:             varchar('vertical', { length: 255 }),
    territory:            varchar('territory', { length: 255 }),
    team:                 varchar('team', { length: 255 }),
    lostReason:           text('lost_reason'),
    lostCategory:         varchar('lost_category', { length: 255 }),
    lostDate:             varchar('lost_date', { length: 20 }),
    wonDate:              varchar('won_date', { length: 20 }),
    stageChangedDate:     varchar('stage_changed_date', { length: 20 }),
    createdDate:          varchar('created_date', { length: 20 }),
    createdBy:            varchar('created_by', { length: 255 }),
    stageHistory:         jsonb('stage_history').default('[]'),
    comments:             jsonb('comments').default('[]'),
    aiScore:              jsonb('ai_score'),
    createdAt:            timestamp('created_at').notNull().defaultNow(),
    orgId:                text('org_id').notNull(),
    updatedAt:            timestamp('updated_at').notNull().defaultNow(),
});
// ── TASKS ─────────────────────────────────────────────────────────────────────
export const tasks = pgTable('tasks', {
    id:            text('id').primaryKey(),
    title:         varchar('title', { length: 500 }),
    description:   text('description'),
    type:          varchar('type', { length: 100 }),
    dueDate:       varchar('due_date', { length: 20 }),
    dueTime:       varchar('due_time', { length: 10 }),
    reminderDate:  varchar('reminder_date', { length: 20 }),
    reminderTime:  varchar('reminder_time', { length: 10 }),
    assignedTo:    varchar('assigned_to', { length: 255 }),
    priority:      varchar('priority', { length: 20 }),
    status:        varchar('status', { length: 50 }).notNull().default('Open'),
    completed:     boolean('completed').notNull().default(false),
    completedDate: varchar('completed_date', { length: 20 }),
    opportunityId: text('opportunity_id'),
    contactId:     text('contact_id'),
    accountId:     text('account_id'),
    relatedTo:     text('related_to'),
    createdAt:     timestamp('created_at').notNull().defaultNow(),
    orgId:         text('org_id').notNull(),
    updatedAt:     timestamp('updated_at').notNull().defaultNow(),
});
// ── ACTIVITIES ────────────────────────────────────────────────────────────────
export const activities = pgTable('activities', {
    id:            text('id').primaryKey(),
    type:          varchar('type', { length: 100 }),
    date:          varchar('date', { length: 20 }),
    subject:       varchar('subject', { length: 500 }),
    notes:         text('notes'),
    outcome:       varchar('outcome', { length: 255 }),
    duration:      integer('duration'),
    opportunityId: text('opportunity_id'),
    contactId:     text('contact_id'),
    accountId:     text('account_id'),
    author:        varchar('author', { length: 255 }),
    createdAt:     timestamp('created_at').notNull().defaultNow(),
    orgId:         text('org_id').notNull(),
    updatedAt:     timestamp('updated_at').notNull().defaultNow(),
});
// ── SETTINGS ──────────────────────────────────────────────────────────────────
export const settings = pgTable('settings', {
    id:              text('id').primaryKey().default('default'),
    companyName:     varchar('company_name', { length: 255 }),
    companyLogo:     text('company_logo'),
    fiscalYearStart: varchar('fiscal_year_start', { length: 10 }),
    stages:          jsonb('stages').default('[]'),
    taskTypes:       jsonb('task_types').default('[]'),
    painPoints:      jsonb('pain_points').default('[]'),
    verticalMarkets: jsonb('vertical_markets').default('[]'),
    fieldVisibility: jsonb('field_visibility').default('{}'),
    extra:           jsonb('extra').default('{}'),
    orgId:           text('org_id').notNull(),
    updatedAt:       timestamp('updated_at').notNull().defaultNow(),
    // ── NEW: added for Quotes feature ────────────────────────────────────────
    quotesEnabled:   boolean('quotes_enabled').default(false),
});
// ── AUDIT LOG ─────────────────────────────────────────────────────────────────
export const auditLog = pgTable('audit_log', {
    id:         text('id').primaryKey(),
    action:     varchar('action', { length: 50 }).notNull(),
    entityType: varchar('entity_type', { length: 100 }).notNull(),
    entityId:   text('entity_id').notNull(),
    entityName: text('entity_name'),
    detail:     text('detail'),
    userId:     text('user_id'),
    userName:   varchar('user_name', { length: 255 }),
    orgId:      text('org_id').notNull(),
    timestamp:  timestamp('timestamp').notNull().defaultNow(),
});
// ── SPIFF CLAIMS ──────────────────────────────────────────────────────────────
export const spiffClaims = pgTable('spiff_claims', {
    id:              text('id').primaryKey(),
    orgId:           text('org_id').notNull(),
    spiffId:         text('spiff_id').notNull(),
    spiffName:       varchar('spiff_name', { length: 500 }),
    opportunityId:   text('opportunity_id'),
    opportunityName: varchar('opportunity_name', { length: 500 }),
    account:         varchar('account', { length: 255 }),
    repName:         varchar('rep_name', { length: 255 }).notNull(),
    amount:          decimal('amount', { precision: 12, scale: 2 }),
    multiplier:      decimal('multiplier', { precision: 6, scale: 3 }),
    spiffType:       varchar('spiff_type', { length: 50 }),
    dealArr:         decimal('deal_arr', { precision: 12, scale: 2 }),
    status:          varchar('status', { length: 50 }).notNull().default('pending'),
    note:            text('note'),
    claimedAt:       timestamp('claimed_at').notNull().defaultNow(),
    approvedAt:      timestamp('approved_at'),
    approvedBy:      varchar('approved_by', { length: 255 }),
    paidAt:          timestamp('paid_at'),
    createdAt:       timestamp('created_at').notNull().defaultNow(),
    updatedAt:       timestamp('updated_at').notNull().defaultNow(),
});
// ── RECOMMENDATION LOG ────────────────────────────────────────────────────────
export const recommendationLog = pgTable('recommendation_log', {
    id:             text('id').primaryKey(),
    orgId:          text('org_id').notNull(),
    repName:        varchar('rep_name', { length: 255 }).notNull(),
    actionType:     varchar('action_type', { length: 100 }).notNull(),
    opportunityId:  text('opportunity_id'),
    dealName:       varchar('deal_name', { length: 500 }),
    arrAtRisk:      decimal('arr_at_risk', { precision: 12, scale: 2 }),
    stage:          varchar('stage', { length: 100 }),
    signal:         text('signal'),
    dismissedAt:    timestamp('dismissed_at').notNull().defaultNow(),
    outcome:        varchar('outcome', { length: 50 }).notNull().default('pending'),
    resolvedAt:     timestamp('resolved_at'),
    daysToResolve:  integer('days_to_resolve'),
    createdAt:      timestamp('created_at').notNull().defaultNow(),
});
// ── LEADS ─────────────────────────────────────────────────────────────────────
export const leads = pgTable('leads', {
    id:           text('id').primaryKey(),
    firstName:    varchar('first_name', { length: 255 }),
    lastName:     varchar('last_name', { length: 255 }),
    company:      varchar('company', { length: 255 }),
    title:        varchar('title', { length: 255 }),
    email:        varchar('email', { length: 255 }),
    phone:        varchar('phone', { length: 50 }),
    source:       varchar('source', { length: 100 }),
    status:       varchar('status', { length: 50 }).notNull().default('New'),
    score:        integer('score').default(50),
    estimatedARR: decimal('estimated_arr', { precision: 12, scale: 2 }),
    assignedTo:   varchar('assigned_to', { length: 255 }),
    notes:        text('notes'),
    convertedAt:      varchar('converted_at', { length: 30 }),
    firstTouchDate:   varchar('first_touch_date', { length: 30 }),
    createdAt:    timestamp('created_at').notNull().defaultNow(),
    orgId:        text('org_id').notNull(),
    updatedAt:    timestamp('updated_at').notNull().defaultNow(),
});
// ── DASHBOARD CONFIGS ─────────────────────────────────────────────────────────
export const dashboardConfigs = pgTable('dashboard_configs', {
    id:        text('id').primaryKey(),
    userId:    text('user_id').notNull(),
    orgId:     text('org_id').notNull(),
    widgets:   jsonb('widgets').notNull().default('[]'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
});
// ── USER CALENDAR CONNECTIONS ─────────────────────────────────────────────────
export const userCalendarConnections = pgTable('user_calendar_connections', {
    id:                    text('id').primaryKey(),
    userId:                text('user_id').notNull(),
    orgId:                 text('org_id').notNull(),
    provider:              varchar('provider', { length: 20 }).notNull(),
    encryptedRefreshToken: text('encrypted_refresh_token').notNull(),
    calendarEmail:         varchar('calendar_email', { length: 255 }),
    connectedAt:           timestamp('connected_at').notNull().defaultNow(),
    updatedAt:             timestamp('updated_at').notNull().defaultNow(),
});
// ── ORG CALENDAR CONNECTIONS ──────────────────────────────────────────────────
export const orgCalendarConnections = pgTable('org_calendar_connections', {
    id:                    text('id').primaryKey(),
    orgId:                 text('org_id').notNull(),
    provider:              varchar('provider', { length: 20 }).notNull(),
    encryptedRefreshToken: text('encrypted_refresh_token').notNull(),
    calendarName:          varchar('calendar_name', { length: 255 }),
    calendarEmail:         varchar('calendar_email', { length: 255 }),
    connectedAt:           timestamp('connected_at').notNull().defaultNow(),
    connectedBy:           varchar('connected_by', { length: 255 }),
    updatedAt:             timestamp('updated_at').notNull().defaultNow(),
});
// ── API KEYS ──────────────────────────────────────────────────────────────────
export const apiKeys = pgTable('api_keys', {
    id:          text('id').primaryKey(),
    orgId:       text('org_id').notNull(),
    name:        varchar('name', { length: 255 }).notNull(),
    keyHash:     text('key_hash').notNull(),
    keyPrefix:   varchar('key_prefix', { length: 20 }).notNull(),
    scopes:      jsonb('scopes').notNull().default('["read"]'),
    lastUsedAt:  timestamp('last_used_at'),
    createdBy:   varchar('created_by', { length: 255 }),
    createdAt:   timestamp('created_at').notNull().defaultNow(),
    revokedAt:   timestamp('revoked_at'),
    updatedAt:   timestamp('updated_at').notNull().defaultNow(),
});
// ── WEBHOOK SUBSCRIPTIONS ─────────────────────────────────────────────────────
export const webhookSubscriptions = pgTable('webhook_subscriptions', {
    id:          text('id').primaryKey(),
    orgId:       text('org_id').notNull(),
    name:        varchar('name', { length: 255 }).notNull(),
    targetUrl:   text('target_url').notNull(),
    eventTypes:  jsonb('event_types').notNull().default('[]'),
    secret:      text('secret').notNull(),
    active:      boolean('active').notNull().default(true),
    createdBy:   varchar('created_by', { length: 255 }),
    lastFiredAt: timestamp('last_fired_at'),
    lastStatus:  integer('last_status'),
    createdAt:   timestamp('created_at').notNull().defaultNow(),
    updatedAt:   timestamp('updated_at').notNull().defaultNow(),
});

// ── PRODUCTS (PRICE BOOK) ─────────────────────────────────────────────────────
// NEW — added for Quotes feature
// productType: 'recurring' | 'one_time' | 'service'
// unit: 'month' | 'year' | 'user' | 'flat' | 'hour' | 'day'
export const products = pgTable('products', {
    id:           text('id').primaryKey(),
    orgId:        text('org_id').notNull(),
    name:         varchar('name', { length: 255 }).notNull(),
    sku:          varchar('sku', { length: 100 }),
    description:  text('description'),
    productType:  varchar('product_type', { length: 20 }).notNull().default('one_time'),
    listPrice:    decimal('list_price', { precision: 12, scale: 2 }).notNull(),
    minPrice:     decimal('min_price', { precision: 12, scale: 2 }),
    unit:         varchar('unit', { length: 50 }).default('flat'),
    category:     varchar('category', { length: 255 }),
    active:       boolean('active').notNull().default(true),
    sortOrder:    integer('sort_order').default(0),
    createdBy:    varchar('created_by', { length: 255 }),
    createdAt:    timestamp('created_at').notNull().defaultNow(),
    updatedAt:    timestamp('updated_at').notNull().defaultNow(),
});

// ── QUOTES ────────────────────────────────────────────────────────────────────
// NEW — added for Quotes feature
// status: 'Draft' | 'Pending Approval' | 'Approved' | 'Sent' | 'Accepted' | 'Declined' | 'Expired'
// When Accepted, totalValue is synced to opportunity.arr automatically.
export const quotes = pgTable('quotes', {
    id:              text('id').primaryKey(),
    orgId:           text('org_id').notNull(),
    opportunityId:   text('opportunity_id').notNull(),
    quoteNumber:     varchar('quote_number', { length: 50 }).notNull(),
    version:         integer('version').notNull().default(1),
    name:            varchar('name', { length: 500 }),
    status:          varchar('status', { length: 50 }).notNull().default('Draft'),
    validUntil:      varchar('valid_until', { length: 20 }),
    paymentTerms:    varchar('payment_terms', { length: 100 }),
    billingContact:  varchar('billing_contact', { length: 255 }),
    lineItems:       jsonb('line_items').notNull().default('[]'),
    subtotal:        decimal('subtotal', { precision: 12, scale: 2 }),
    dealDiscount:    decimal('deal_discount', { precision: 5, scale: 2 }).default('0'),
    totalValue:      decimal('total_value', { precision: 12, scale: 2 }),
    recurringValue:  decimal('recurring_value', { precision: 12, scale: 2 }),
    oneTimeValue:    decimal('one_time_value', { precision: 12, scale: 2 }),
    notes:           text('notes'),
    approvalNote:    text('approval_note'),
    approvedBy:      varchar('approved_by', { length: 255 }),
    approvedAt:      timestamp('approved_at'),
    sentAt:          timestamp('sent_at'),
    acceptedAt:      timestamp('accepted_at'),
    syncedToOpp:     boolean('synced_to_opp').default(false),
    createdBy:       varchar('created_by', { length: 255 }),
    createdAt:       timestamp('created_at').notNull().defaultNow(),
    updatedAt:       timestamp('updated_at').notNull().defaultNow(),
});

export const savedReports = pgTable('saved_reports', {
    id:          text('id').primaryKey(),
    orgId:       text('org_id').notNull(),
    ownerId:     text('owner_id').notNull(),
    ownerName:   varchar('owner_name', { length: 255 }),
    name:        varchar('name', { length: 255 }).notNull(),
    description: text('description'),
    source:      varchar('source', { length: 100 }),
    dims:        jsonb('dims'),
    metrics:     jsonb('metrics'),
    chartType:   varchar('chart_type', { length: 50 }),
    filters:     jsonb('filters'),
    config:      jsonb('config'),
    isShared:    boolean('is_shared').default(false),
    createdAt:   timestamp('created_at').notNull().defaultNow(),
    updatedAt:   timestamp('updated_at').notNull().defaultNow(),
});
